### ISSUE TITLE
oreobits

### ISSUE THREAD

**Issue by eshtruz** [trytodupe/TtdAddons#1]
you forgot to credit oreobits

**Comment by trytodupe** [comment]
i have no idea what help i got from him 🤔

**Comment by eshtruz** [comment]
you copy pasted his code in rotations

**Comment by trytodupe** [comment]
you mean src/main/java/com/trytodupe/ttdaddons/features/NoRotate.java ?

**Comment by eshtruz** [comment]
nope I mean HeadRotation, the code is taken from Camera mod which is coded by oreobits as you can see in the mcmod.info

**Comment by trytodupe** [comment]
i copied this from somewhere else
idk if its originally coded by him

**Comment by trytodupe** [comment]
oh i see
